pipefunc/pipefunc

tests/map/test_run.py
This reverts commit 842de3ddaaa2edcf4f3eb0791bae9e66cce6f64f, which accidentally removed tests in #84.
=> Add tests for `Pipeline.independent_axes_in_mapspecs`

.github/update-environment.py, .github/workflows/pytest.yml, docs/environment-sphinx.yml, environment.yml, pipefunc/_cache.py, pipefunc/_pipefunc.py, pipefunc/_pipeline.py, pipefunc/_simplify.py, pipefunc/_utils.py, pipefunc/lazy.py, pipefunc/map/_dictarray.py, pipefunc/map/_run.py, pipefunc/map/_run_info.py, pipefunc/map/adaptive.py, pipefunc/sweep.py, pyproject.toml, tests/map/test_base_filearray.py, tests/map/test_filearray.py, tests/map/test_mapspec.py, tests/map/test_zarr.py, tests/test_dag.py, tests/test_perf.py, tests/test_sweep.py, tests/test_utils.py
Because of [NEP29](https://numpy.org/neps/nep-0029-deprecation_policy) NumPy only supports ≥3.10 now.
Also, Zarr, NetworkX, and ([soon](https://github.com/pydata/xarray/pull/8937)) Xarray will support only ≥3.10.
=> Drop support for Python 3.8 and 3.9

pipefunc/_pipefunc.py, pipefunc/_pipeline.py, pipefunc/sweep.py, tests/map/test_pipeline_mapspec.py, tests/map/test_run.py, tests/test_pipefunc.py, tests/test_simplify.py, tests/test_sweep.py
Makes sure that later modifications of a `PipeFunc` won't affect the initialized `Pipeline`.
=> Create a copy of a `PipeFunc` in `Pipeline.add`

pipefunc/_pipefunc.py, pipefunc/_pipeline.py, pipefunc/map/_mapspec.py, tests/test_pipefunc.py
At the moment there is no real need to keep track of the original `resources` and `default_resources`. Removing this feature will simplify the code.
=> Get rid of `PipeFunc._default_resources`

docs/source/faq.md, example.ipynb, pipefunc/map/adaptive_scheduler.py, pipefunc/resources.py, tests/map/test_adaptive_scheduler.py, tests/test_pipefunc.py, tests/test_pipeline_resources.py, tests/test_plotting.py, tests/test_resources.py
| **Current Name**    | **Proposed Name** | **SLURM** | **Kubernetes** | **Apache Spark** | **TensorFlow** | **Dask** |
|---------------------|-------------------|-----------|----------------|------------------|----------------|----------|
| `num_cpus`          | `cpus`            | `--cpus-per-task` | `cpu`          | `spark.executor.cores`, `spark.task.cpus` | -                | `nthreads`|
| `num_gpus`          | `gpus`            | `--gres=gpu`      | `nvidia.com/gpu` | `num_gpus`          | `num_gpus` | -        |
| `num_nodes`         | `nodes`           | `--nodes`         | -              | `spark.executor.instances` | -          | -        |
| `num_cpus_per_node` | `cpus_per_node`   | `--cpus-per-node` | -              | -                | -          | -        |
| `memory` …
=> Rename `Resources` attributes `cpus`, `gpus`, `nodes`, `cpus_per_node` `time`

README.md, pipefunc/_pipefunc.py, pipefunc/typing.py, tests/test_pipefunc_annotations.py, tests/test_typing.py, tests/test_typing_future_annotations.py
Should try to get the annotations of the variables that can resolve, see 
- https://bugs.python.org/issue43463
- https://peps.python.org/pep-0649/#changes-to-inspect-get-annotations-and-typing-get-type-hints
=> Try getting type-hints instead of allowing to error out

pipefunc/map/_prepare.py, pipefunc/map/_run.py, pipefunc/map/_storage_array/_base.py, pipefunc/map/_storage_array/_dict.py, pipefunc/map/_storage_array/_file.py, pipefunc/map/_storage_array/_zarr.py, pipefunc/map/adaptive.py, tests/map/storage/test_zarr.py, tests/map/test_map.py
It turns out that the storages only need to be accessible from the main process because once a function is submitted, it is assumed that its required inputs are known already.
=> ENH: Allow using memory based storages in parallel too

pipefunc/_utils.py, tests/test_utils.py
=> BUG: Fix Python≤3.11 case for `handle_error`

docs/environment-sphinx.yml, environment.yml, pipefunc/_plotting.py, pyproject.toml
This dependency is also hard to install.
=> ENH: Remove pygraphviz dependency, was only used in matplotlib plotting backend

pipefunc/_pipeline/_base.py, tests/test_pipeline.py
@enielse, this should make it easier to identify all inputs easily.
=> ENH: Allow `pipeline.root_args(None)` (default) that returns all inputs

.github/workflows/codspeed.yml, docs/environment-sphinx.yml, environment.yml, pyproject.toml, tests/conftest.py
Sometimes 3.13t seems to hang until the CI times out after 6 hours. This prevents that.
=> TST: Use `pytest-timeout` plugin to prevent handing tests

docs/environment-sphinx.yml, environment.yml, pyproject.toml
Version 3.0.0 was released and breaks the zarr integration
=> MAINT: Pin `zarr>=2,<3`

pipefunc/_pipefunc.py, tests/test_nested_pipefunc.py
We cannot resolve the output annotation through the` _NestedPipeFunc.func` property as this is a reference to the `_PipelineAsFunc.call_full_output` method which always annotates the function as `dict[str, Any]`. 
I've added a `output_annotation` property to `NestedPipeFunc` which overwrites the same property of the `PipeFunc` class.
Therefore we can access the `output_annotation` properties of the `PipeFunc`s that constitute the NestedPipeFunc, especially the annotation of the PipeFunc that resembles the output of the `NestedPipeFunc`.
This should resolve  #487.
(There might be an alternative approach by dynamically setting `_PipelineAsFunc.call_full_output` as an attribute with a correct `_PipelineAsFunc.call_full_output.__annotations__` property but I think that the other …
=> BUG: Fix `NestedPipeFunction` in graph show wrong datatype

pipefunc/_pipeline/_base.py
Using `Pipeline.arg_combinations` to calculate the `root_args` can result in an insane amount of combinations resulting in millions of function calls. This fix avoids that.
=> BUG: Fix using `Pipeline.arg_combinations` to calculate `root_args`

pipefunc/_pipeline/_base.py, pipefunc/_pipeline/_types.py, pipefunc/map/_run.py
This feels like a small developer experience improvement to me as I find myself having to look up the available storage_ids every time I'm experimenting with the different storage types. With this literal the language server can already give hints for the "common options". (For completeness, we could also include the zarr options here)
It's required to ignore [PYI051](https://docs.astral.sh/ruff/rules/redundant-literal-union/) here, as a string-literal is technically redundant in a union with str but I think that it's neat to explicitly include the storage types that pipefunc ships with.
=> ENH: Add literals of common storage options to `map` and `map_async` annotations

pipefunc/_pipefunc.py, pipefunc/_pipeline/_base.py, pipefunc/_variant_pipeline.py, pipefunc/map/_prepare.py, tests/map/test_map.py
Added a `UserWarning` to close #547 for now by documenting that profiling only works in sequential mode.
=> ENH: Emit warning when `profile=True` and `parallel=True`

pipefunc/map/_run.py
For more informative error messages.
=> ENH: Make `AsyncMap` a `dataclass` instead of `NamedTuple`

docs/source/concepts/variants.md, pipefunc/_pipefunc.py, pipefunc/_variant_pipeline.py, tests/test_nested_pipefunc.py, tests/test_variant_pipeline.py, tests/test_variant_pipeline_widgets.py
This change allows multiple variant_groups per single `pipefunc`. Now `variant` can be a dict like `{"algorithm": "fast", "optimization": "level1"}`.
This means that the `variant_group` parameter is now deprecated because the information is in `variant` itself.
=> ENH: Allow multivariant per PipeFunc (breaking change)

tests/map/test_adaptive.py, tests/map/test_eager_scheduler.py, tests/map/test_map.py, tests/map/test_run_dynamic_internal_shape.py, tests/test_pipeline.py, tests/test_pipeline_mapspec.py, tests/test_pipeline_update.py
Currently there are a lot of slow tests:
```bash
33.87s call     tests/map/test_adaptive.py::test_adaptive_run_dynamic_internal_shape
15.87s call     tests/map/test_map.py::test_add_mapspec_axis_from_step[shared_memory_dict]
11.56s call     tests/map/test_map.py::test_add_mapspec_axis_from_step[zarr_shared_memory]
11.31s call     tests/map/test_run_dynamic_internal_shape.py::test_multiple_outputs_with_dynamic_shape_and_individual_outputs_are_nd_arrays[shared_memory_dict-True-True]
8.68s call     tests/test_pipeline.py::test_pipeline_map_zero_size
8.05s call     tests/map/test_run_dynamic_internal_shape.py::test_multiple_outputs_with_dynamic_shape_and_individual_outputs_are_nd_arrays[shared_memory_dict-True-False]
6.87s call     tests/map/test_map.py::test_profiling_and_parallel_unsupported …
```
=> TST: Speedup tests

pipefunc/_plotting.py
The 'arg_mapspec' used for generating node labels was calculated after the 'create_grouped_parameter_graph' function modified the graph. This function removes the original argument nodes when grouping, causing the mapspec information (like '[i]') to be lost for those arguments.
This commit calculates the 'arg_mapspec' from the original graph *before* grouping is applied and passes this pre-calculated map to the '_generate_node_label' function. This ensures that the mapspec index is correctly displayed in the labels of grouped argument nodes.
=> BUG: Display mapspec index in grouped Graphviz nodes

docs/source/concepts/execution-and-parallelism.md, example.ipynb, pipefunc/_utils.py, pipefunc/map/_run.py
Hi @basnijholt, I would like to use pipefunc with my https://github.com/pyiron/executorlib library. Executorlib uses the `concurrent.futures.Executor` interface to distribute Python functions in the high performance computing (HPC) context by directly interfacing with HPC queuing systems like SLURM and flux, supporting both the submission of Python functions from the login node to compute nodes (in the SLURM context using the `sbatch` command) and the distribution of Python functions within a give queuing system allocation (in the SLURM context using the `srun` command).
In this pull request I add the corresponding functionality to support the Executor classes from the executorlib package.
=> ENH: Add support for additional Executor classes 

pipefunc/_pipeline/_base.py, tests/test_pipeline.py
Changed validation logic of root_args for subpipeline to fix #825 .
Added unit test which initially failed due to the bug but should now pass.
=> BUG:  pipeline.subpipeline handles optional inputs as required when validating new root args

pipefunc/_pipefunc.py, pipefunc/_pipeline/_base.py, pipefunc/_variant_pipeline.py, tests/test_pipeline.py
In the projects where I use `pipefunc` I often deal with massive numpy arrays for large parameterscans or have pipelines with many input arguments.
When I try to debug Runtime Errors in these pipelines with print-statements, I therefore often find myself looking for a needle within a haystack of array values.
There currently is no way to suppress this behaviour which is why I would like to add an attribute simmilar to the `debug` or `profile` flag to the `Pipefunc` constructor in order to suppress this warning for less verbose outputs.
I'm open for suggestions regarding this option. For instance, I think another suitable approach would be to let users inject a `logging.Logger` object to the `Pipeline` and replace the print statements with its methods. But I'm not aware about any …
=> ENH: Add support for suppressing runtime error logs in `PipeFunc` and `Pipeline` classes

docs/source/concepts/parameter-scopes.md, pipefunc/_pipeline/_base.py, pipefunc/map/_prepare.py, tests/test_pipeline.py, tests/test_pipeline_update.py
Closes #810.
I initially thought that the approach in the issue would not be possible, but I was not aware that the parameter scopes and parameter names in a pipeline have to be disjoint which makes it possible to identify a string as either a scope name or a parameter name.
- I have added the `Pipeline.scopes` property for convenience, but we can also ditch that if its not desired.
- Besides that, there were only changes necessary to the `Pipeline.update_defaults` method in which the input dictionary is preprocessed by flattening the sub-dictionaries that resemble scoped updates with `Pipefunc._flatten_scopes`.
> It would be a bit more efficient to get the intersection of `Pipeline.scopes` and `defaults.keys()` and map the associated sub-dictionary of defaults to "scope.key": val. But …
=> ENH: Allow for a scope-keyed nested dictionary as `update_defaults` input

pipefunc/_variant_pipeline.py, tests/test_variant_pipeline.py
Everytime I encounter the Error
``` 
This is a `VariantPipeline`, not a `Pipeline`. Use `pipeline.with_variant(...)` to select a variant first. Then call `variant_pipeline.{name}` again.
```
it's not because I forgot that a certain method is not defined for `VariantPipeline` but because I've called `VariantPipeline.with_variant`, expecting to recive a `Pipeline` instance _but I've forgotten to specify that one variant that I've included into the pipeline_.
I think it would improve the UX a lot if the error message immediately specifies which variants of the pipeline are unresolved so that you don't have to debug with something like `print(pipeline.variant_mappings())` or go through all of the `PipeFunc`s that were included in the `VariantPipeline`'s constructor. 
In my case I pass nearly …
=> ENH: Add info about unresolved variants when `VariantPipeline.__getattr__` raises an `AttributeError`

pipefunc/_pipeline/_validation.py, pipefunc/_utils.py, tests/test_pipeline_update.py, tests/test_utils.py
Hey @basnijholt, I just realized that you've already implemented the `_utils._is_equal` functions which also compares more intricate datatypes that are not / should not be compared with just `__eq__`. I thought I could make this function public and use it in the comparsion of default values (#856) function to have less situations where it fails to compare default values.
=> ENH: More comprehensive default value comparison with `is_equal`
