pipefunc/pipefunc

- pipefunc/map/LICENSE
- pipefunc/map/_filearray.py
- pipefunc/map/_mapspec.py
- pipefunc/map/serialize.py
I have copied over the following files from https://github.com/microsoft/aiida-dynamic-workflows:
- https://github.com/microsoft/aiida-dynamic-workflows/blob/4d452ed3be4192dc5b2c8f40690f82c3afcaa7a8/aiida_dynamic_workflows/common/array.py
- https://github.com/microsoft/aiida-dynamic-workflows/blob/4d452ed3be4192dc5b2c8f40690f82c3afcaa7a8/aiida_dynamic_workflows/common/mapspec.py
- https://github.com/microsoft/aiida-dynamic-workflows/blob/4d452ed3be4192dc5b2c8f40690f82c3afcaa7a8/aiida_dynamic_workflows/common/serialize.py
- https://github.com/microsoft/aiida-dynamic-workflows/blob/4d452ed3be4192dc5b2c8f40690f82c3afcaa7a8/LICENSE
Then in https://github.com/basnijholt/pipefunc/pull/22 changes will be applied to these files.
> Add `MapSpec` and `FileBasedObjectArray` `from aiida-dynamic-workflows`

- pipefunc/map/_filearray.py
- tests/map/test_filearray.py
Back-ported from https://github.com/basnijholt/pipefunc/pull/85.
> Fix bug and refactor `FileArray`

- example.ipynb
- pipefunc/_pipeline.py
- pipefunc/map/_run.py
- pipefunc/map/adaptive.py
- tests/map/test_adaptive.py
- tests/map/test_run.py
Back-ported from https://github.com/basnijholt/pipefunc/pull/85.
> Rename `manual_shapes` to `internal_shapes`

- pipefunc/_pipeline.py
- tests/map/test_run.py
- tests/test_pipefunc.py
Back-ported from https://github.com/basnijholt/pipefunc/pull/85.
> Allow calling `add_mapspec_axis` on multiple parameters

- pipefunc/_pipeline.py
- tests/test_pipefunc.py
> Add `Pipeline.replace`

- .github/update-environment.py
- docs/environment-sphinx.yml
- docs/source/conf.py
- environment.yml
- pipefunc/_pipeline.py
- pipefunc/map/_run.py
- pipefunc/map/_run_info.py
- pipefunc/map/_storage_base.py
- pipefunc/map/adaptive.py
- pyproject.toml
https://github.com/executablebooks/MyST-NB/pull/604
> Documentation MyST fixes and style changes

- docs/source/conf.py
- pipefunc/_cache.py
- pipefunc/_perf.py
- pipefunc/_pipefunc.py
- pipefunc/_pipeline.py
- pipefunc/_simplify.py
- pipefunc/_sweep.py
- pipefunc/map/_filearray.py
- pipefunc/map/_mapspec.py
- pipefunc/map/_run.py
- pipefunc/map/adaptive.py
- pipefunc/map/zarr.py
- pyproject.toml
Seemed initially blocked by 
- https://github.com/numpy/numpydoc/issues/356
- https://github.com/sphinx-doc/sphinx/issues/7077
- https://github.com/numpy/numpydoc/issues/251#issuecomment-766178060
However, fixed by finding this comment https://github.com/sphinx-doc/sphinx/issues/7077#issuecomment-1571885203 which pointed to https://github.com/tox-dev/sphinx-autodoc-typehints/pull/311
> Use `sphinx-autodoc-typehints`

- docs/environment-sphinx.yml
- docs/source/reference/index.md
- environment.yml
- pipefunc/map/adaptive.py
- pipefunc/map/adaptive_scheduler.py
- pipefunc/resources.py
- pyproject.toml
- tests/map/test_adaptive.py
- tests/map/test_adaptive_scheduler.py
- tests/test_resources.py
Depends on https://github.com/basnijholt/adaptive-scheduler/pull/224
> Add Adaptive Scheduler integration

- docs/source/conf.py
- docs/source/faq.md
- example.ipynb
- pipefunc/_pipefunc.py
- pipefunc/_pipeline.py
- tests/test_pipefunc.py
> Allow renaming `output_name` in `update_renames`

- pipefunc/_pipeline.py
- tests/test_pipefunc.py
> Allow parameterless functions in a Pipeline

- README.md
I used the following Keyboard Maestro macro to record this: [Type text.kmmacros.txt](https://github.com/user-attachments/files/16821374/Type.text.kmmacros.txt)
Then I ran `asciinema rec  --overwrite pipefunc-demo.cast` and uploaded the resulting file.
> Add `asciinema` recording

- README.md
Using `asciinema rec  --overwrite --env="PATH=/Users/bas.nijholt/micromamba/envs/pipefunc/bin" --command=ipython demo2.cast`
New code:
```
from pipefunc import pipefunc, Pipeline
@pipefunc(output_name="c")  # we're saying that this function outputs 'c'
def f(a: int, b: int) -> int:
return a + b
@pipefunc(output_name="d")
def g(b: int, c: int) -> int:  # this function takes 'c' from the previous function
return b * c
pipeline = Pipeline([f, g])
pipeline("d", a=1, b=2)
pipeline("c", a=1, b=2)
pipeline = Pipeline([f, g], profile=True, debug=True)
pipeline("d", a=1, b=2)
pipeline.print_profiling_stats()
import numpy as np
@pipefunc(output_name="c", mapspec="a[i], b[j] -> c[i, j]")
def f(a: int, b: int) -> int:
return a + b
@pipefunc(output_name="mean")
def g(c: np.ndarray) -> np.float64: …
```
> Update `asciinema` recording

- pipefunc/cache.py
https://github.com/grantjenks/python-diskcache/blob/ebfa37cd99d7ef716ec452ad8af4b4276a8e2233/diskcache/core.py#L139-L163
> ENH: Use pickle for cache key, inspired by `python-diskcache` package

- docs/environment-sphinx.yml
- example.ipynb
- pyproject.toml
Adds:
- Example: Sensor Data Processing Pipeline
- Example: Image Processing Workflow Example with `mapspec`
- Example: Natural Language Processing Pipeline for Text Summarization
- Example: Weather Simulation and Analysis Pipeline with `xarray`
> DOC: Add additional examples to the tutorial

- .github/update-environment.py
- docs/environment-sphinx.yml
- docs/source/faq.md
- pyproject.toml
https://github.com/executablebooks/MyST-NB/pull/604 was merged and made it into [v1.1.2](https://github.com/executablebooks/MyST-NB/releases/tag/v1.1.2).
> DOC: Rely on latest release of MyST

- pipefunc/_pipefunc.py
- tests/test_pipefunc.py
> ENH: Include class name in `PipeFunc.__name__`

- pipefunc/_pipefunc.py
- pipefunc/_pipeline/_base.py
- pipefunc/map/_mapspec.py
- pipefunc/map/_prepare.py
- pipefunc/map/_run.py
- pipefunc/map/_run_info.py
- pipefunc/map/_shapes.py
- pipefunc/map/_types.py
- pipefunc/map/adaptive.py
Should make the https://github.com/pipefunc/pipefunc/pull/381 diff much smaller.
> Define `ShapeDict`, `ShapeTuple`, `UserShapeDict` types

- pipefunc/_adaptive.py
- pipefunc/map/_adaptive_lazy_sequence_learner.py
- tests/test_adaptive_lazy_sequence_learner.py
Taken from https://github.com/pipefunc/pipefunc/pull/381.
> MAINT: Move `LazySequenceLearner` to separate module

- pipefunc/map/_prepare.py
- pipefunc/map/_run.py
Simplifies https://github.com/pipefunc/pipefunc/pull/395
> ENH: Make `executor` a dict internally always

- docs/source/conf.py
- example.ipynb
- pipefunc/_pipeline/_base.py
Will change it back once https://github.com/manzt/anywidget/pull/628 is merged and https://github.com/manzt/anywidget/issues/613 solved)
Currently the tutorial page is 60 MB which is prohibitively large.
> DOC: Set default plotting backend in docs to graphviz

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
Inspired by https://github.com/a5chin/python-uv.
> ENH: Add a `.devcontainer` for VS Code based on `uv`

- pipefunc/map/_mapspec.py
- tests/map/test_map.py
- tests/map/test_run_dynamic_internal_shape.py
Depends on https://github.com/pipefunc/pipefunc/pull/448
> ENH: Automatically set `internal_shape=("?", ...)`

- pipefunc/helpers.py
- tests/test_helpers.py
> ENH: Add `helpers.get_attribute_factory`

- .github/workflows/pytest-micromamba.yml
- .github/workflows/pytest-uv.yml
> CI: Revert `pull_request_target:`

- pipefunc/_pipeline/_base.py
- pipefunc/_utils.py
- pipefunc/map/_adaptive_scheduler_slurm_executor.py
- pipefunc/map/_run.py
- tests/map/test_map_chunking.py
- tests/test_utils.py
@LennartGevers, what do you think about this?
> ENH: Add auto-chunksize heuristic

- pipefunc/_pipefunc.py
- pipefunc/_pipeline/_base.py
- tests/map/test_map.py
- tests/test_pipefunc.py
Closes https://github.com/pipefunc/pipefunc/issues/195
> ENH: Allow setting `NestedPipeFunc(..., function_name="customname")`

- tests/test_plotting.py
`graphviz_anywidget` was updated
> TST: Fix `tests/test_plotting.py::test_plotting_widget`

- docs/source/conf.py
- example.ipynb
> DOC: Fix URL of tutorial in uv tip

- pipefunc/map/_adaptive_scheduler_slurm_executor.py
- pipefunc/map/_run.py
Related Adaptive Scheduler PR: https://github.com/basnijholt/adaptive-scheduler/pull/256
> BUG: Fix case with `SlurmExecutor.finalize()` but nothing was submitted

- pipefunc/map/_adaptive_scheduler_slurm_executor.py
- tests/map/test_adaptive_slurm_executor.py
> BUG: Fix correct number of jobs for both `resources_scope` options

- pipefunc/_pipefunc.py
- tests/map/test_adaptive_slurm_executor.py
> BUG: Fix missing `resources_scope` in `NestedPipeFunc`

- .github/generate-release-notes.py
- CHANGELOG.md
> DOC: Update `CHANGELOG.md` until v0.60.0

- pipefunc/_pipeline/_base.py
- tests/test_pipeline.py
> ENH: Add `Pipeline.run(..., allow_unused=True)`

- pipefunc/_widgets/progress.py
- tests/test_widgets_tracker.py
> ENH: Use unique border colors different scopes for progress bars

- pipefunc/_widgets/progress.py
- tests/test_widgets_tracker.py
> ENH: Set background colors per scope in `ProgressTracker` widget

- pipefunc/_widgets/progress.py
- tests/test_widgets_tracker.py
https://github.com/user-attachments/assets/ae886f9e-acbf-46b3-a112-e5f8095224e4
> ENH: Add a slight pulse animation when progress bar reaches 100%

- pipefunc/_widgets/progress_ipywidgets.py
> ENH: Dynamically set the width of the description in the progress bar

- pipefunc/helpers.py
https://github.com/microsoft/vscode-jupyter/issues/16739
> BUG: Workaround for VS Code ipywidgets issue

- pipefunc/__init__.py
- pipefunc/_pipefunc.py
- pipefunc/_pipeline/_base.py
- pipefunc/exceptions.py
- tests/test_pipefunc.py
Prepare for https://github.com/pipefunc/pipefunc/pull/842
> MAINT: Move `ErrorSnapshot` to `exceptions.py`
